// 5-assignment/src/views/RegisterView.tsx
import React, { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useAppDispatch, useAppSelector } from '@/store/hooks'
import { register } from '@/features/auth/authSlice'

export default function RegisterView() {
  const dispatch = useAppDispatch()
  const { status, error } = useAppSelector((s) => s.auth)
  const nav = useNavigate()
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault()
    try {
      await dispatch(register({ username, password })).unwrap()
      nav('/', { replace: true })
    } catch {
      // handled
    }
  }

  return (
    <div style={{ maxWidth: 420 }}>
      <h2>Register</h2>
      <form onSubmit={onSubmit}>
        <label>
          Username
          <input value={username} onChange={(e) => setUsername(e.target.value)} />
        </label>
        <label>
          Password
          <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} />
        </label>
        <button disabled={status === 'loading'} type="submit">
          Create account
        </button>
        {error && <p style={{ color: 'crimson' }}>{error}</p>}
      </form>
      <p>
        Already have an account? <Link to="/login">Login</Link>
      </p>
    </div>
  )
}

// 2-assignment/client/src/views/RegisterView.vue
<template>
  <section class="auth">
    <h1>Register</h1>

    <form @submit.prevent="onSubmit">
      <div class="field">
        <label>Username</label>
        <input v-model="username" autocomplete="username" required />
      </div>

      <div class="field">
        <label>Password</label>
        <input
          v-model="password"
          type="password"
          autocomplete="new-password"
          required
        />
      </div>

      <div class="field">
        <label>Repeat password</label>
        <input
          v-model="repeatPassword"
          type="password"
          autocomplete="new-password"
          required
        />
      </div>

      <p v-if="error" class="error">{{ error }}</p>

      <button type="submit">Create account</button>
    </form>

    <p class="hint">
      Already registered?
      <RouterLink to="/login">Login</RouterLink>
    </p>
  </section>
</template>

<script setup lang="ts">
import { ref } from "vue";
import { useRouter } from "vue-router";
import { useAuthStore } from "@/stores/authStore";

const auth = useAuthStore();
const router = useRouter();

const username = ref("");
const password = ref("");
const repeatPassword = ref("");
const error = ref("");

const onSubmit = () => {
  error.value = "";
  if (password.value !== repeatPassword.value) {
    error.value = "Passwords do not match";
    return;
  }

  try {
    auth.register(username.value, password.value);
    router.push("/");
  } catch (e: any) {
    error.value = e?.message || "Registration failed";
  }
};
</script>

<style scoped>
.auth {
  max-width: 320px;
}
.field {
  margin-bottom: 0.75rem;
  display: flex;
  flex-direction: column;
}
.error {
  color: #c00;
  margin-bottom: 0.75rem;
}
.hint {
  margin-top: 1rem;
}
</style>
